[build]
builder = "NIXPACKS"
buildCommand = "cd xydo_backend_clean && npm install"

[deploy]
startCommand = "cd xydo_backend_clean && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
